### ISSUE TITLE
vitest/expect-expect errors on xited/skipped tests

### ISSUE THREAD

**Issue by GNRSN** [veritem/eslint-plugin-vitest#238]
We usually commit a bunch of empty test stubs with `ìt.skip`prefix (since vitest isn't fond of empty tests either) to list validation which we want to add. It's kind of anoying that `expect-expect` errors here, requiring an `@eslint-disable` pragma, as it is otherwise a good rule.

As I see it, a test which is explicitly not to be ran should never *require* an expect? 

One could maybe make the argument that skipped tests shouldn't require validation at all since they're not being actively maintained, however i think that this rule in particular is the most evident. 

If this is a matter of opinion, maybe it could be introduced as a configuration option?

**Comment by veritem** [comment]
Your point make sense to me. When I designed this rule `expect-expect`. I didn't think much about this kind of behaviors to be honest with you. I don't get a point why it can throw that error since a rule is skipped. I'll fix it when I get time this weekend. 

Thank you so much for bringing this up.

**Comment by veritem** [comment]
@GNRSN Would you mind giving the latest version a try? I hope it fixes your question.

**Comment by GNRSN** [comment]
@veritem Works great, thank you!
